# Generated by Django 4.2.7 on 2024-01-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='user',
            new_name='authorUser',
        ),
    ]
